### ISSUE TITLE
Page down

### ISSUE THREAD

**Issue by sinnlosername** [blacked/eth0.me#1]
Are you still the current owner of the domain? If so, do you have any plans to bring the site back online? If not, would you sell the domain?

**Comment by adubkov** [comment]
Ah, sorry, this is my friend domain. I will ask him.

**Comment by sinnlosername** [comment]
Okay, thanks. If he doesn't want to host it anymore I could do so so others and also some of my application can continue use it.

**Comment by MeGysssTaa** [comment]
Hello,
Any news on this?

**Comment by adubkov** [comment]
@stephen-mw Hey man, please take a look on that. Do you still own it?

**Comment by stephen-mw** [comment]
Sorry I let the domain expire and I'm no longer the owner. Not sure who owns it now.
